// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SecondSplitWise.DBContext;

namespace SecondSplitWise.Migrations
{
    [DbContext(typeof(SecondSplitWiseContext))]
    [Migration("20181001092029_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SecondSplitWise.Model.Expense", b =>
                {
                    b.Property<int>("BillId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("Amount");

                    b.Property<string>("BillName");

                    b.Property<DateTime>("CreatedDate");

                    b.Property<int>("CreatorId");

                    b.Property<int?>("GroupId");

                    b.Property<byte[]>("Image");

                    b.HasKey("BillId");

                    b.HasIndex("CreatorId");

                    b.HasIndex("GroupId");

                    b.ToTable("Expense");
                });

            modelBuilder.Entity("SecondSplitWise.Model.ExpenseMember", b =>
                {
                    b.Property<int>("BillMemberId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("AmountToPay");

                    b.Property<int>("Billid");

                    b.Property<int?>("SharedMemberId");

                    b.HasKey("BillMemberId");

                    b.HasIndex("Billid");

                    b.HasIndex("SharedMemberId");

                    b.ToTable("ExpenseMember");
                });

            modelBuilder.Entity("SecondSplitWise.Model.Friend", b =>
                {
                    b.Property<int>("FriendListId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("FriendId");

                    b.Property<int?>("UserId");

                    b.HasKey("FriendListId");

                    b.HasIndex("FriendId");

                    b.HasIndex("UserId");

                    b.ToTable("Friend");
                });

            modelBuilder.Entity("SecondSplitWise.Model.Group", b =>
                {
                    b.Property<int>("GroupId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedDate");

                    b.Property<int>("CreatorId");

                    b.Property<string>("GroupName");

                    b.HasKey("GroupId");

                    b.HasIndex("CreatorId");

                    b.ToTable("Group");
                });

            modelBuilder.Entity("SecondSplitWise.Model.GroupMember", b =>
                {
                    b.Property<int>("GroupMemberId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Group_Id");

                    b.Property<int?>("User_Id");

                    b.HasKey("GroupMemberId");

                    b.HasIndex("Group_Id");

                    b.HasIndex("User_Id");

                    b.ToTable("GroupMember");
                });

            modelBuilder.Entity("SecondSplitWise.Model.Payer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BillId");

                    b.Property<decimal>("PaidAmount");

                    b.Property<int?>("PayerId");

                    b.HasKey("Id");

                    b.HasIndex("BillId");

                    b.HasIndex("PayerId");

                    b.ToTable("Payer");
                });

            modelBuilder.Entity("SecondSplitWise.Model.Settlement", b =>
                {
                    b.Property<int>("SettlementId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("GroupId");

                    b.Property<int>("PayerId")
                        .HasColumnName("Payer_Person");

                    b.Property<int?>("SharedMemberId")
                        .HasColumnName("Requestor_Person");

                    b.Property<decimal>("TotalAmount");

                    b.HasKey("SettlementId");

                    b.HasIndex("GroupId");

                    b.HasIndex("PayerId");

                    b.HasIndex("SharedMemberId");

                    b.ToTable("Settlement");
                });

            modelBuilder.Entity("SecondSplitWise.Model.Transactions", b =>
                {
                    b.Property<int>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedDate");

                    b.Property<int?>("GroupId");

                    b.Property<decimal>("PaidAmount");

                    b.Property<int>("TransPayersId");

                    b.Property<int?>("TransReceiversId");

                    b.HasKey("TransactionId");

                    b.HasIndex("GroupId");

                    b.HasIndex("TransPayersId");

                    b.HasIndex("TransReceiversId");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("SecondSplitWise.Model.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email");

                    b.Property<string>("Password");

                    b.Property<string>("UserName");

                    b.HasKey("UserId");

                    b.ToTable("User");
                });

            modelBuilder.Entity("SecondSplitWise.Model.Expense", b =>
                {
                    b.HasOne("SecondSplitWise.Model.User", "User")
                        .WithMany("Bills")
                        .HasForeignKey("CreatorId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("SecondSplitWise.Model.Group", "Group")
                        .WithMany("Bills")
                        .HasForeignKey("GroupId");
                });

            modelBuilder.Entity("SecondSplitWise.Model.ExpenseMember", b =>
                {
                    b.HasOne("SecondSplitWise.Model.Expense", "Bill")
                        .WithMany("BillMembers")
                        .HasForeignKey("Billid")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("SecondSplitWise.Model.User", "User")
                        .WithMany("BillMembers")
                        .HasForeignKey("SharedMemberId");
                });

            modelBuilder.Entity("SecondSplitWise.Model.Friend", b =>
                {
                    b.HasOne("SecondSplitWise.Model.User", "friend")
                        .WithMany("Friends")
                        .HasForeignKey("FriendId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("SecondSplitWise.Model.User", "user")
                        .WithMany("Users")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("SecondSplitWise.Model.Group", b =>
                {
                    b.HasOne("SecondSplitWise.Model.User", "User")
                        .WithMany("Groups")
                        .HasForeignKey("CreatorId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("SecondSplitWise.Model.GroupMember", b =>
                {
                    b.HasOne("SecondSplitWise.Model.Group", "Group")
                        .WithMany("groupMembers")
                        .HasForeignKey("Group_Id")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("SecondSplitWise.Model.User", "User")
                        .WithMany("groupMembers")
                        .HasForeignKey("User_Id");
                });

            modelBuilder.Entity("SecondSplitWise.Model.Payer", b =>
                {
                    b.HasOne("SecondSplitWise.Model.Expense", "Bill")
                        .WithMany("Payers")
                        .HasForeignKey("BillId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("SecondSplitWise.Model.User", "User")
                        .WithMany("Payersdata")
                        .HasForeignKey("PayerId");
                });

            modelBuilder.Entity("SecondSplitWise.Model.Settlement", b =>
                {
                    b.HasOne("SecondSplitWise.Model.Group", "groupsId")
                        .WithMany("SettlmentData")
                        .HasForeignKey("GroupId");

                    b.HasOne("SecondSplitWise.Model.User", "Payer")
                        .WithMany("Payers")
                        .HasForeignKey("PayerId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("SecondSplitWise.Model.User", "SharedMember")
                        .WithMany("SharedMembers")
                        .HasForeignKey("SharedMemberId");
                });

            modelBuilder.Entity("SecondSplitWise.Model.Transactions", b =>
                {
                    b.HasOne("SecondSplitWise.Model.Group", "groupsId")
                        .WithMany("Transactions")
                        .HasForeignKey("GroupId");

                    b.HasOne("SecondSplitWise.Model.User", "TransPayers")
                        .WithMany("TPayers")
                        .HasForeignKey("TransPayersId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("SecondSplitWise.Model.User", "TransReceivers")
                        .WithMany("TReceivers")
                        .HasForeignKey("TransReceiversId");
                });
#pragma warning restore 612, 618
        }
    }
}
